// <auto-generated />
using System;
using FitCity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitCity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FitCityDbContext))]
    [Migration("20260121202152_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitCity.Domain.Entities.CentralAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CentralAdministrators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            AssignedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(273),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.CheckInLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScannedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("ScannedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckInLogs");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0c0c0c0-c0c0-c0c0-c0c0-c0c0c0c0c0c0"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(573),
                            Title = "Training chat"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0d0d0d0-d0d0-d0d0-d0d0-d0d0d0d0d0d0"),
                            ConversationId = new Guid("c0c0c0c0-c0c0-c0c0-c0c0-c0c0c0c0c0c0"),
                            JoinedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(595),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("e0e0e0e0-e0e0-e0e0-e0e0-e0e0e0e0e0e0"),
                            ConversationId = new Guid("c0c0c0c0-c0c0-c0c0-c0c0-c0c0c0c0c0c0"),
                            JoinedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(597),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Main Street 1",
                            City = "Sarajevo",
                            Description = "Main gym location.",
                            IsActive = true,
                            Name = "FitCity Downtown",
                            PhoneNumber = "111-222"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "River Road 10",
                            City = "Sarajevo",
                            Description = "Second gym location.",
                            IsActive = true,
                            Name = "FitCity East",
                            PhoneNumber = "333-444"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("GymId", "UserId")
                        .IsUnique();

                    b.ToTable("GymAdministrators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            AssignedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(301),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("GymPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Description = "One month access.",
                            DurationMonths = 1,
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Monthly",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            Description = "Three months access.",
                            DurationMonths = 3,
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Quarterly",
                            Price = 129.99m
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymTrainer", b =>
                {
                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("GymId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("GymTrainers");

                    b.HasData(
                        new
                        {
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TrainerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GymPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("GymPlanId");

                    b.HasIndex("UserId", "GymId");

                    b.ToTable("Memberships", t =>
                        {
                            t.HasCheckConstraint("CK_Membership_Status", "[Status] IN (1,2,3,4)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            EndDateUtc = new DateTime(2025, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            GymPlanId = new Guid("20202020-2020-2020-2020-202020202020"),
                            StartDateUtc = new DateTime(2024, 12, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.MembershipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GymPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("GymPlanId");

                    b.HasIndex("UserId", "GymId");

                    b.ToTable("MembershipRequests", t =>
                        {
                            t.HasCheckConstraint("CK_MembershipRequest_Status", "[Status] IN (1,2,3,4)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            GymPlanId = new Guid("10101010-1010-1010-1010-101010101010"),
                            RequestedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(361),
                            Status = 1,
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0f0f0f0-f0f0-f0f0-f0f0-f0f0f0f0f0f0"),
                            Content = "Welcome to FitCity!",
                            ConversationId = new Guid("c0c0c0c0-c0c0-c0c0-c0c0-c0c0c0c0c0c0"),
                            SenderUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAtUtc = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("TrainingSessionId")
                        .IsUnique()
                        .HasFilter("[TrainingSessionId] IS NOT NULL");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Method", "[Method] IN (1,2,3)");

                            t.HasCheckConstraint("CK_Payment_Target", "([MembershipId] IS NOT NULL AND [TrainingSessionId] IS NULL) OR ([MembershipId] IS NULL AND [TrainingSessionId] IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            Amount = 30m,
                            Method = 1,
                            PaidAtUtc = new DateTime(2024, 12, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrainingSessionId = new Guid("80808080-8080-8080-8080-808080808080")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredWorkoutTime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.QRCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.ToTable("QRCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            ExpiresAtUtc = new DateTime(2025, 1, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            MembershipId = new Guid("40404040-4040-4040-4040-404040404040"),
                            TokenHash = "token-hash-1"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("UserId", "TrainerId", "GymId")
                        .IsUnique()
                        .HasFilter("[GymId] IS NOT NULL");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "[Rating] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0a0a0a0-a0a0-a0a0-a0a0-a0a0a0a0a0a0"),
                            Comment = "Great session.",
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(546),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Rating = 5,
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("b0b0b0b0-b0b0-b0b0-b0b0-b0b0b0b0b0b0"),
                            Comment = "Nice class.",
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 824, DateTimeKind.Utc).AddTicks(549),
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Rating = 4,
                            TrainerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            UserId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Certifications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Bio = "Strength coach.",
                            Certifications = "NSCA",
                            IsActive = true,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Bio = "Yoga and mobility.",
                            Certifications = "RYT-200",
                            IsActive = true,
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainerSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("TrainerId", "StartUtc", "EndUtc");

                    b.ToTable("TrainerSchedules", t =>
                        {
                            t.HasCheckConstraint("CK_TrainerSchedule_Time", "[EndUtc] > [StartUtc]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("60606060-6060-6060-6060-606060606060"),
                            EndUtc = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("70707070-7070-7070-7070-707070707070"),
                            EndUtc = new DateTime(2025, 1, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.HasIndex("TrainerId", "StartUtc", "EndUtc");

                    b.ToTable("TrainingSessions", t =>
                        {
                            t.HasCheckConstraint("CK_TrainingSession_Status", "[Status] IN (1,2,3,4)");

                            t.HasCheckConstraint("CK_TrainingSession_Time", "[EndUtc] > [StartUtc]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("80808080-8080-8080-8080-808080808080"),
                            EndUtc = new DateTime(2025, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartUtc = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9784),
                            Email = "central@fitcity.local",
                            FullName = "Central Admin",
                            PasswordHash = "HASHED:central",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9797),
                            Email = "admin@gym.local",
                            FullName = "Gym Admin",
                            PasswordHash = "HASHED:gymadmin",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9799),
                            Email = "trainer1@gym.local",
                            FullName = "Trainer One",
                            PasswordHash = "HASHED:trainer1",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9801),
                            Email = "trainer2@gym.local",
                            FullName = "Trainer Two",
                            PasswordHash = "HASHED:trainer2",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9803),
                            Email = "user1@gym.local",
                            FullName = "User One",
                            PasswordHash = "HASHED:user1",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9805),
                            Email = "user2@gym.local",
                            FullName = "User Two",
                            PasswordHash = "HASHED:user2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9807),
                            Email = "user3@gym.local",
                            FullName = "User Three",
                            PasswordHash = "HASHED:user3",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9810),
                            Email = "user4@gym.local",
                            FullName = "User Four",
                            PasswordHash = "HASHED:user4",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAtUtc = new DateTime(2026, 1, 21, 20, 21, 49, 823, DateTimeKind.Utc).AddTicks(9812),
                            Email = "user5@gym.local",
                            FullName = "User Five",
                            PasswordHash = "HASHED:user5",
                            Role = 1
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.CentralAdministrator", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("CentralAdministratorProfile")
                        .HasForeignKey("FitCity.Domain.Entities.CentralAdministrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.CheckInLog", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("CheckIns")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "ScannedByUser")
                        .WithMany("ScannedCheckIns")
                        .HasForeignKey("ScannedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("ScannedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymAdministrator", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Administrators")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("GymAdministratorProfile")
                        .HasForeignKey("FitCity.Domain.Entities.GymAdministrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPlan", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Plans")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymTrainer", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("GymTrainers")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("GymTrainers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Membership", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Memberships")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.GymPlan", "GymPlan")
                        .WithMany("Memberships")
                        .HasForeignKey("GymPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.MembershipRequest", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.GymPlan", "GymPlan")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("GymPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Message", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Payment", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Membership", "Membership")
                        .WithMany("Payments")
                        .HasForeignKey("MembershipId");

                    b.HasOne("FitCity.Domain.Entities.TrainingSession", "TrainingSession")
                        .WithOne("Payment")
                        .HasForeignKey("FitCity.Domain.Entities.Payment", "TrainingSessionId");

                    b.Navigation("Membership");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Preference", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("FitCity.Domain.Entities.Preference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.QRCode", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Membership", "Membership")
                        .WithOne("QRCode")
                        .HasForeignKey("FitCity.Domain.Entities.QRCode", "MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Review", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Reviews")
                        .HasForeignKey("GymId");

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Reviews")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Trainer", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("TrainerProfile")
                        .HasForeignKey("FitCity.Domain.Entities.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainerSchedule", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("TrainerSchedules")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainingSession", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Gym", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("CheckIns");

                    b.Navigation("GymTrainers");

                    b.Navigation("MembershipRequests");

                    b.Navigation("Memberships");

                    b.Navigation("Plans");

                    b.Navigation("Reviews");

                    b.Navigation("TrainerSchedules");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPlan", b =>
                {
                    b.Navigation("MembershipRequests");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Membership", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("QRCode");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("GymTrainers");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainingSession", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.User", b =>
                {
                    b.Navigation("CentralAdministratorProfile");

                    b.Navigation("CheckIns");

                    b.Navigation("Conversations");

                    b.Navigation("GymAdministratorProfile");

                    b.Navigation("MembershipRequests");

                    b.Navigation("Memberships");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Preference");

                    b.Navigation("Reviews");

                    b.Navigation("ScannedCheckIns");

                    b.Navigation("TrainerProfile");

                    b.Navigation("TrainingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
