// <auto-generated />
using System;
using FitCity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitCity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FitCityDbContext))]
    [Migration("20260122113919_AddGymPhotosAndLocations")]
    partial class AddGymPhotosAndLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitCity.Domain.Entities.CentralAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CentralAdministrators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a9a9a9a-9a9a-9a9a-9a9a-9a9a9a9a9a9a"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2698),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.CheckInLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckInAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScannedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("ScannedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckInLogs");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95959595-9595-9595-9595-959595959595"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(3094),
                            Title = "Training chat"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96969696-9696-9696-9696-969696969696"),
                            ConversationId = new Guid("95959595-9595-9595-9595-959595959595"),
                            JoinedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(3116),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("97979797-9797-9797-9797-979797979797"),
                            ConversationId = new Guid("95959595-9595-9595-9595-959595959595"),
                            JoinedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(3119),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WorkHours")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Zmaja od Bosne 12",
                            City = "Sarajevo",
                            Description = "Central location near Marijin Dvor.",
                            IsActive = true,
                            Name = "FitCity Downtown",
                            PhoneNumber = "033-100-100",
                            PhotoUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "06:00-22:00"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "Hrasnicka Cesta 10",
                            City = "Sarajevo",
                            Description = "Spacious gym with wellness zone.",
                            IsActive = true,
                            Name = "FitCity Ilidza",
                            PhoneNumber = "033-200-200",
                            PhotoUrl = "https://images.unsplash.com/photo-1554344728-77cf90d9ed26?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "06:00-23:00"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Address = "Saraci 45",
                            City = "Sarajevo",
                            Description = "Boutique studio in the old town.",
                            IsActive = true,
                            Name = "FitCity Bascarsija",
                            PhoneNumber = "033-300-300",
                            PhotoUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "07:00-21:00"
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            Address = "Zvornička 1",
                            City = "Sarajevo",
                            Description = "Neighborhood gym with boxing zone.",
                            IsActive = true,
                            Latitude = 43.850099999999998,
                            Longitude = 18.395800000000001,
                            Name = "FitCity Grbavica",
                            PhoneNumber = "033-400-400",
                            PhotoUrl = "https://images.unsplash.com/photo-1571019613914-85f342c55f42?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "06:30-22:30"
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            Address = "Zmaja od Bosne 45",
                            City = "Sarajevo",
                            Description = "Modern gym with strength and cardio zones.",
                            IsActive = true,
                            Latitude = 43.852899999999998,
                            Longitude = 18.401199999999999,
                            Name = "GYM NOVO SARAJEVO",
                            PhoneNumber = "033-510-510",
                            PhotoUrl = "https://images.unsplash.com/photo-1534367610401-9f5ed68180aa?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "Mon–Fri 06:00–22:30, Sat 08:00–20:00, Sun 10:00–18:00"
                        },
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            Address = "Grbavicka 12",
                            City = "Sarajevo",
                            Description = "Neighborhood gym with group classes.",
                            IsActive = true,
                            Latitude = 43.851300000000002,
                            Longitude = 18.402799999999999,
                            Name = "GYM GRBAVICA",
                            PhoneNumber = "033-520-520",
                            PhotoUrl = "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "Mon–Fri 06:30–22:00, Sat 08:00–19:00, Sun 10:00–16:00"
                        },
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            Address = "Marijin Dvor 5",
                            City = "Sarajevo",
                            Description = "Fitness center with spa and recovery.",
                            IsActive = true,
                            Latitude = 43.857700000000001,
                            Longitude = 18.412700000000001,
                            Name = "GYM BOSNA",
                            PhoneNumber = "033-530-530",
                            PhotoUrl = "https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "Mon–Fri 05:30–23:00, Sat 07:00–21:00, Sun 09:00–19:00"
                        },
                        new
                        {
                            Id = new Guid("17171717-1717-1717-1717-171717171717"),
                            Address = "Bascarsija 3",
                            City = "Sarajevo",
                            Description = "Old town gym with functional training.",
                            IsActive = true,
                            Latitude = 43.859400000000001,
                            Longitude = 18.430199999999999,
                            Name = "TERETANA GRADA",
                            PhoneNumber = "033-540-540",
                            PhotoUrl = "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&w=800&q=80",
                            WorkHours = "Mon–Fri 07:00–21:00, Sat 08:00–18:00, Sun 10:00–16:00"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymAdministrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("GymId", "UserId")
                        .IsUnique();

                    b.ToTable("GymAdministrators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b9b9b9b-9b9b-9b9b-9b9b-9b9b9b9b9b9b"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2726),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("9c9c9c9c-9c9c-9c9c-9c9c-9c9c9c9c9c9c"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2728),
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222223")
                        },
                        new
                        {
                            Id = new Guid("9d9d9d9d-9d9d-9d9d-9d9d-9d9d9d9d9d9d"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2729),
                            GymId = new Guid("12121212-1212-1212-1212-121212121212"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222224")
                        },
                        new
                        {
                            Id = new Guid("9e9e9e9e-9e9e-9e9e-9e9e-9e9e9e9e9e9e"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2730),
                            GymId = new Guid("13131313-1313-1313-1313-131313131313"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222225")
                        },
                        new
                        {
                            Id = new Guid("9f9f9f9f-9f9f-9f9f-9f9f-9f9f9f9f9f9f"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2731),
                            GymId = new Guid("14141414-1414-1414-1414-141414141414"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222226")
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2732),
                            GymId = new Guid("15151515-1515-1515-1515-151515151515"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222227")
                        },
                        new
                        {
                            Id = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2733),
                            GymId = new Guid("16161616-1616-1616-1616-161616161616"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222228")
                        },
                        new
                        {
                            Id = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            AssignedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2734),
                            GymId = new Guid("17171717-1717-1717-1717-171717171717"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222229")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "SortOrder")
                        .IsUnique();

                    b.ToTable("GymPhotos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18181818-1818-1818-1818-181818181818"),
                            GymId = new Guid("14141414-1414-1414-1414-141414141414"),
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1534367610401-9f5ed68180aa?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("19191919-1919-1919-1919-191919191919"),
                            GymId = new Guid("14141414-1414-1414-1414-141414141414"),
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1550345332-09e3ac987658?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a"),
                            GymId = new Guid("14141414-1414-1414-1414-141414141414"),
                            SortOrder = 3,
                            Url = "https://images.unsplash.com/photo-1554284126-aa88f22d0a1d?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("1b1b1b1b-1b1b-1b1b-1b1b-1b1b1b1b1b1b"),
                            GymId = new Guid("15151515-1515-1515-1515-151515151515"),
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("1c1c1c1c-1c1c-1c1c-1c1c-1c1c1c1c1c1c"),
                            GymId = new Guid("15151515-1515-1515-1515-151515151515"),
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1549576490-b0b4831ef60a?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("1d1d1d1d-1d1d-1d1d-1d1d-1d1d1d1d1d1d"),
                            GymId = new Guid("15151515-1515-1515-1515-151515151515"),
                            SortOrder = 3,
                            Url = "https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("1e1e1e1e-1e1e-1e1e-1e1e-1e1e1e1e1e1e"),
                            GymId = new Guid("16161616-1616-1616-1616-161616161616"),
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("1f1f1f1f-1f1f-1f1f-1f1f-1f1f1f1f1f1f"),
                            GymId = new Guid("16161616-1616-1616-1616-161616161616"),
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1554344728-77cf90d9ed26?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            GymId = new Guid("16161616-1616-1616-1616-161616161616"),
                            SortOrder = 3,
                            Url = "https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("21212121-2121-2121-2121-212121212121"),
                            GymId = new Guid("17171717-1717-1717-1717-171717171717"),
                            SortOrder = 1,
                            Url = "https://images.unsplash.com/photo-1526401485004-46910ecc8e51?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222230"),
                            GymId = new Guid("17171717-1717-1717-1717-171717171717"),
                            SortOrder = 2,
                            Url = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80"
                        },
                        new
                        {
                            Id = new Guid("23232323-2323-2323-2323-232323232323"),
                            GymId = new Guid("17171717-1717-1717-1717-171717171717"),
                            SortOrder = 3,
                            Url = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("GymPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Description = "One month access.",
                            DurationMonths = 1,
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Monthly",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            Description = "Three months access.",
                            DurationMonths = 3,
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsActive = true,
                            Name = "Quarterly",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            Description = "Annual membership.",
                            DurationMonths = 12,
                            GymId = new Guid("12121212-1212-1212-1212-121212121212"),
                            IsActive = true,
                            Name = "Annual",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            Description = "10 session pack.",
                            DurationMonths = 3,
                            GymId = new Guid("13131313-1313-1313-1313-131313131313"),
                            IsActive = true,
                            Name = "Drop-in 10",
                            Price = 89.99m
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymTrainer", b =>
                {
                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("GymId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("GymTrainers");

                    b.HasData(
                        new
                        {
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TrainerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GymId = new Guid("12121212-1212-1212-1212-121212121212"),
                            TrainerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GymId = new Guid("13131313-1313-1313-1313-131313131313"),
                            TrainerId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            TrainerId = new Guid("01010101-0101-0101-0101-010101010101"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            TrainerId = new Guid("02020202-0202-0202-0202-020202020202"),
                            AssignedAtUtc = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GymPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("GymPlanId");

                    b.HasIndex("UserId", "GymId");

                    b.ToTable("Memberships", t =>
                        {
                            t.HasCheckConstraint("CK_Membership_Status", "[Status] IN (1,2,3,4)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("60606060-6060-6060-6060-606060606060"),
                            EndDateUtc = new DateTime(2025, 4, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            GymPlanId = new Guid("10101010-1010-1010-1010-101010101010"),
                            StartDateUtc = new DateTime(2024, 12, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.MembershipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GymPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("GymPlanId");

                    b.HasIndex("UserId", "GymId");

                    b.ToTable("MembershipRequests", t =>
                        {
                            t.HasCheckConstraint("CK_MembershipRequest_Status", "[Status] IN (1,2,3,4)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            GymPlanId = new Guid("10101010-1010-1010-1010-101010101010"),
                            RequestedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(2804),
                            Status = 1,
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98989898-9898-9898-9898-989898989898"),
                            Content = "Welcome to FitCity!",
                            ConversationId = new Guid("95959595-9595-9595-9595-959595959595"),
                            SenderUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SentAtUtc = new DateTime(2025, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("TrainingSessionId")
                        .IsUnique()
                        .HasFilter("[TrainingSessionId] IS NOT NULL");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Method", "[Method] IN (1,2,3)");

                            t.HasCheckConstraint("CK_Payment_Target", "([MembershipId] IS NOT NULL AND [TrainingSessionId] IS NULL) OR ([MembershipId] IS NULL AND [TrainingSessionId] IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("92929292-9292-9292-9292-929292929292"),
                            Amount = 30m,
                            Method = 1,
                            PaidAtUtc = new DateTime(2024, 12, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrainingSessionId = new Guid("90909090-9090-9090-9090-909090909090")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredWorkoutTime")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.QRCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.ToTable("QRCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70707070-7070-7070-7070-707070707070"),
                            ExpiresAtUtc = new DateTime(2025, 1, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            MembershipId = new Guid("60606060-6060-6060-6060-606060606060"),
                            TokenHash = "token-hash-1"
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("UserId", "TrainerId", "GymId")
                        .IsUnique()
                        .HasFilter("[GymId] IS NOT NULL");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "[Rating] BETWEEN 1 AND 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("93939393-9393-9393-9393-939393939393"),
                            Comment = "Great session.",
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(3010),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Rating = 5,
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("94949494-9494-9494-9494-949494949494"),
                            Comment = "Nice class.",
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(3012),
                            GymId = new Guid("12121212-1212-1212-1212-121212121212"),
                            Rating = 4,
                            TrainerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Certifications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Bio = "Strength coach focused on compound lifts.",
                            Certifications = "NSCA CPT",
                            HourlyRate = 40m,
                            IsActive = true,
                            PhotoUrl = "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=600&q=80",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Bio = "Yoga and mobility specialist.",
                            Certifications = "RYT-200",
                            HourlyRate = 35m,
                            IsActive = true,
                            PhotoUrl = "https://images.unsplash.com/photo-1549576490-b0b4831ef60a?auto=format&fit=crop&w=600&q=80",
                            UserId = new Guid("33333333-3333-3333-3333-333333333334")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Bio = "HIIT and conditioning coach.",
                            Certifications = "ACE CPT",
                            HourlyRate = 38m,
                            IsActive = true,
                            PhotoUrl = "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
                            UserId = new Guid("33333333-3333-3333-3333-333333333335")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Bio = "Powerlifting and strength cycles.",
                            Certifications = "IPF Level 1",
                            HourlyRate = 45m,
                            IsActive = true,
                            PhotoUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
                            UserId = new Guid("33333333-3333-3333-3333-333333333336")
                        },
                        new
                        {
                            Id = new Guid("01010101-0101-0101-0101-010101010101"),
                            Bio = "Pilates and core stability sessions.",
                            Certifications = "Pilates Mat",
                            HourlyRate = 32m,
                            IsActive = true,
                            PhotoUrl = "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
                            UserId = new Guid("33333333-3333-3333-3333-333333333337")
                        },
                        new
                        {
                            Id = new Guid("02020202-0202-0202-0202-020202020202"),
                            Bio = "Boxing fundamentals and conditioning.",
                            Certifications = "Boxing Level 2",
                            HourlyRate = 42m,
                            IsActive = true,
                            PhotoUrl = "https://images.unsplash.com/photo-1508341591423-4347099e1f19?auto=format&fit=crop&w=600&q=80",
                            UserId = new Guid("33333333-3333-3333-3333-333333333338")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainerSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("TrainerId", "StartUtc", "EndUtc");

                    b.ToTable("TrainerSchedules", t =>
                        {
                            t.HasCheckConstraint("CK_TrainerSchedule_Time", "[EndUtc] > [StartUtc]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("80808080-8080-8080-8080-808080808080"),
                            EndUtc = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("81818181-8181-8181-8181-818181818181"),
                            EndUtc = new DateTime(2025, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("82828282-8282-8282-8282-828282828282"),
                            EndUtc = new DateTime(2025, 1, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("12121212-1212-1212-1212-121212121212"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("83838383-8383-8383-8383-838383838383"),
                            EndUtc = new DateTime(2025, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("13131313-1313-1313-1313-131313131313"),
                            IsAvailable = false,
                            StartUtc = new DateTime(2025, 1, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("84848484-8484-8484-8484-848484848484"),
                            EndUtc = new DateTime(2025, 1, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("01010101-0101-0101-0101-010101010101")
                        },
                        new
                        {
                            Id = new Guid("85858585-8585-8585-8585-858585858585"),
                            EndUtc = new DateTime(2025, 1, 4, 19, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            StartUtc = new DateTime(2025, 1, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            TrainerId = new Guid("02020202-0202-0202-0202-020202020202")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId");

                    b.HasIndex("TrainerId", "StartUtc", "EndUtc");

                    b.ToTable("TrainingSessions", t =>
                        {
                            t.HasCheckConstraint("CK_TrainingSession_Status", "[Status] IN (1,2,3,4)");

                            t.HasCheckConstraint("CK_TrainingSession_Time", "[EndUtc] > [StartUtc]");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            EndUtc = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            StartUtc = new DateTime(2025, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TrainerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            UserId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("91919191-9191-9191-9191-919191919191"),
                            EndUtc = new DateTime(2025, 1, 3, 18, 0, 0, 0, DateTimeKind.Utc),
                            GymId = new Guid("12121212-1212-1212-1212-121212121212"),
                            StartUtc = new DateTime(2025, 1, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TrainerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            UserId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1817),
                            Email = "central@fitcity.local",
                            FullName = "Central Admin",
                            PasswordHash = "HASHED:central",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1834),
                            Email = "admin.downtown@fitcity.local",
                            FullName = "Downtown Admin",
                            PasswordHash = "HASHED:gymadmin1",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1837),
                            Email = "admin.ilidza@fitcity.local",
                            FullName = "Ilidza Admin",
                            PasswordHash = "HASHED:gymadmin2",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1898),
                            Email = "admin.bascarsija@fitcity.local",
                            FullName = "Bascarsija Admin",
                            PasswordHash = "HASHED:gymadmin3",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1901),
                            Email = "admin.grbavica@fitcity.local",
                            FullName = "Grbavica Admin",
                            PasswordHash = "HASHED:gymadmin4",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1904),
                            Email = "trainer1@gym.local",
                            FullName = "Amina Hadzic",
                            PasswordHash = "HASHED:trainer1",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1906),
                            Email = "trainer2@gym.local",
                            FullName = "Marko Kovac",
                            PasswordHash = "HASHED:trainer2",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1908),
                            Email = "trainer3@gym.local",
                            FullName = "Elma Smajic",
                            PasswordHash = "HASHED:trainer3pass",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333336"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1910),
                            Email = "trainer4@gym.local",
                            FullName = "Ivan Juric",
                            PasswordHash = "HASHED:trainer4pass",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333337"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1913),
                            Email = "trainer5@gym.local",
                            FullName = "Sara Kostic",
                            PasswordHash = "HASHED:trainer5pass",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333338"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1915),
                            Email = "trainer6@gym.local",
                            FullName = "Nedim Hasic",
                            PasswordHash = "HASHED:trainer6pass",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1917),
                            Email = "admin.novosarajevo@fitcity.local",
                            FullName = "Novo Sarajevo Admin",
                            PasswordHash = "HASHED:gymnovo1",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1919),
                            Email = "admin.grbavica@fitcity.local",
                            FullName = "Grbavica Admin",
                            PasswordHash = "HASHED:gymgrb1",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222228"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1922),
                            Email = "admin.bosna@fitcity.local",
                            FullName = "Bosna Admin",
                            PasswordHash = "HASHED:gymbosna1",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222229"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1924),
                            Email = "admin.grada@fitcity.local",
                            FullName = "Grada Admin",
                            PasswordHash = "HASHED:gymgrada1",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1926),
                            Email = "user1@gym.local",
                            FullName = "User One",
                            PasswordHash = "HASHED:user1pass",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1928),
                            Email = "user2@gym.local",
                            FullName = "User Two",
                            PasswordHash = "HASHED:user2pass",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1931),
                            Email = "user3@gym.local",
                            FullName = "User Three",
                            PasswordHash = "HASHED:user3pass",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1933),
                            Email = "user4@gym.local",
                            FullName = "User Four",
                            PasswordHash = "HASHED:user4pass",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAtUtc = new DateTime(2026, 1, 22, 11, 39, 18, 491, DateTimeKind.Utc).AddTicks(1935),
                            Email = "user5@gym.local",
                            FullName = "User Five",
                            PasswordHash = "HASHED:user5pass",
                            Role = 1
                        });
                });

            modelBuilder.Entity("FitCity.Domain.Entities.CentralAdministrator", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("CentralAdministratorProfile")
                        .HasForeignKey("FitCity.Domain.Entities.CentralAdministrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.CheckInLog", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("CheckIns")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "ScannedByUser")
                        .WithMany("ScannedCheckIns")
                        .HasForeignKey("ScannedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("ScannedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymAdministrator", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Administrators")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("GymAdministratorProfile")
                        .HasForeignKey("FitCity.Domain.Entities.GymAdministrator", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPhoto", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Photos")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPlan", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Plans")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymTrainer", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("GymTrainers")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("GymTrainers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Membership", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Memberships")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.GymPlan", "GymPlan")
                        .WithMany("Memberships")
                        .HasForeignKey("GymPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.MembershipRequest", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.GymPlan", "GymPlan")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("GymPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("MembershipRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("GymPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Message", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Payment", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Membership", "Membership")
                        .WithMany("Payments")
                        .HasForeignKey("MembershipId");

                    b.HasOne("FitCity.Domain.Entities.TrainingSession", "TrainingSession")
                        .WithOne("Payment")
                        .HasForeignKey("FitCity.Domain.Entities.Payment", "TrainingSessionId");

                    b.Navigation("Membership");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Preference", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("FitCity.Domain.Entities.Preference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.QRCode", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Membership", "Membership")
                        .WithOne("QRCode")
                        .HasForeignKey("FitCity.Domain.Entities.QRCode", "MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Review", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("Reviews")
                        .HasForeignKey("GymId");

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Reviews")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Trainer", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithOne("TrainerProfile")
                        .HasForeignKey("FitCity.Domain.Entities.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainerSchedule", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("TrainerSchedules")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainingSession", b =>
                {
                    b.HasOne("FitCity.Domain.Entities.Gym", "Gym")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitCity.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Sessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCity.Domain.Entities.User", "User")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Trainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Gym", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("CheckIns");

                    b.Navigation("GymTrainers");

                    b.Navigation("MembershipRequests");

                    b.Navigation("Memberships");

                    b.Navigation("Photos");

                    b.Navigation("Plans");

                    b.Navigation("Reviews");

                    b.Navigation("TrainerSchedules");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.GymPlan", b =>
                {
                    b.Navigation("MembershipRequests");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Membership", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("QRCode");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("GymTrainers");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.TrainingSession", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("FitCity.Domain.Entities.User", b =>
                {
                    b.Navigation("CentralAdministratorProfile");

                    b.Navigation("CheckIns");

                    b.Navigation("Conversations");

                    b.Navigation("GymAdministratorProfile");

                    b.Navigation("MembershipRequests");

                    b.Navigation("Memberships");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Preference");

                    b.Navigation("Reviews");

                    b.Navigation("ScannedCheckIns");

                    b.Navigation("TrainerProfile");

                    b.Navigation("TrainingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
